[project]
name = "operar-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=2.0.0",
    "pdfplumber>=0.11.9",
    "streamlit>=1.36.0",
    "yfinance>=0.2.40",
]
